### ISSUE TITLE
Understanding mirrored BAF (problematic with LOH sample)

### ISSUE THREAD

**Issue by mpschr** [etal/cnvkit#105]
I have a hard time understanding how the function `mirrored_baf_median` works:

```python
def mirrored_baf_median(vals):
    shift = np.median(np.abs(vals - .5))
    if np.median(vals) > .5:
        return .5 + shift
    else:
        return .5 - shift
```

If I understand correctly, the idea is to return all VAF in a way so they are > 0.05, correct?

I have observed a problem with this function for a sample with LOH. Neighbouring segments get returned a baf value either near-0 or near-1 (arbitrarily) because all the SNVs in the segment are homozygous due to the LOH and the `np.median(vals)` is oscillating around  0.5

I have fixed that on my copy of `cnvkit` changing the function to the one below which corrects the problem for the above sample. I am not sure though what "features" get lost this way
```python
def mirrored_baf_median(vals):
    shift = np.median(np.abs(vals - .5))
    return .5 + shift
```

**Comment by etal** [comment]
You probably want `cnvlib.vary.VariantArray.mirrored_baf(tumor_boost=False)` instead of `export.mirrored_baf_median`. 

In `cnvkit.py export nexus-ogt`, where SNPs are grouped by copy ratio bin, we want to show the median b-allele frequency within each bin so it looks similar to plotting the original SNPs -- but the BAFs within a bin could be both above and below 0.5, so plain median would hide LOH. This function takes the mirrored BAF median, but mirrors the value above or below 0.5 in the same direction as the majority of BAFs.

This way, if you have a tumor sample with normal contamination, and some somatic or false-positive SNV calls mixed in with the SNPs, then you'll see the true SNP BAFs clustered where they should be, both above and below 0.5, and the lower-frequency SNVs that probably shouldn't have been included are all shown will low VAF (y-axis) values, which a molecular pathologist reviewing the plots will intuitively recognize.

For `cnvkit.py call`, you'll see in the code (`cnvlib.do_call`) that the short version is commented out just above the line where `export.mirrored_baf_median` is used. Similar rationale. Feel free to switch which line is commented in your local checkout of the cnvkit code; either way is valid.

(In `cnvkit.py scatter -v`, the SNP VAFs are shown as they are, not grouped by bin, and you'll see the segments are displayed both above and below 0.5, similar to commercial software for viewing SNP array data like Nexus Copy Number and BlueFuse.)

**Comment by mpschr** [comment]
Hi @etal, thanks for the explanations.

I am not sure if we are talking about the same issue here - so I will just elaborate a bit and you can tell me if everything behaves correctly:

It seems to me that the baf-values in the table returned by `do_call` are misleading and influencing the cn1 results. I show my example for chr1 in a sample, where the all three segments in chr1 look the same in the VAF - scatter plot, but have different results in the result table.

```
|-------------+-----------+-----------+------+---------+--------+-----------+----+-----+------|
|  chromosome | start     | end       | gene | log2    | probes | baf       | cn | cn1 | cn2  |
|-------------+-----------+-----------+------+---------+--------+-----------+----+-----+------|
|  1          | 740001    | 149820000 | -    | -0.0138 | 5957   | 0.973274  | 2  | 2   | 0    |
|  1          | 149840001 | 211500000 | -    | 0.0322  | 3039   | 0.0186451 | 2  | 0   | 2    |
|  1          | 211500001 | 249220000 | -    | -0.0253 | 1834   | 0.0232558 | 2  | 0   | 2    |

```

![image](https://cloud.githubusercontent.com/assets/1090105/15065999/969fe9de-1365-11e6-9305-2ba8352e97c3.png)


Meanwhile the second version of the function above, the output changes to the following - which somehow makes more sense to me. Maybe it is still as you expected above?

```
|-------------+-----------+-----------+------+---------+--------+----------+----+-----+------|
|  chromosome | start     | end       | gene | log2    | probes | baf      | cn | cn1 | cn2  |
|-------------+-----------+-----------+------+---------+--------+----------+----+-----+------|
|  1          | 740001    | 149820000 | -    | -0.0138 | 5957   | 0.973274 | 2  | 2   | 0    |
|  1          | 149840001 | 211500000 | -    | 0.0322  | 3039   | 0.981355 | 2  | 2   | 0    |
|  1          | 211500001 | 249220000 | -    | -0.0253 | 1834   | 0.976744 | 2  | 2   | 0    |

```

**Comment by etal** [comment]
OK. I can change `call` and `do_call` to always handle `cn1` as the allele with higher copy number, since the CNV calls are unphased. That can be done without flipping the BAF values; I'm still not sure what to do about those, but I'm tempted to leave them as they are since `call` also works on .cnr files where a bin might cover just one SNP. Are there any outside conventions related to this that you can point to?

**Comment by mpschr** [comment]
Hi

I guess the same treatment for all, makes the most sense.
One thing which is difficult is, when there is a complete loss and maybe one or two normal cell reads are available which in that case actually should be near-0. Apart from that, I am not aware of any conventions on what to do with few SNPs. 
In any case, one convenient option is to supply a `min_snps` argument whose default option can be easily adapted by any user.

Hope I could help.
Michael
