### ISSUE TITLE
Reference coverage construction issues for chrY

### ISSUE THREAD

**Issue by tskir** [etal/cnvkit#115]
Hi Eric,

There appears to be some problem with how chrY reference coverage is calculated. To demonstrate it, I wrote a small script (using real world data would be tedious) which generates a few hundred samples (200 male + 200 female) with 10 regions on chromosomes 1, X and Y each in CNN format. Coverage for each bin is independently random and follows the same general distribution, so after constructing reference we expect to get similar mean and spread for all of the regions. Here's what I actually get when I construct a reference from these samples (average mean and average spread are calculated across all regions on given chromosome):

*200 male + 200 female samples*

|chromosome|avg. mean|avg. spread|
|---|---|---|
|1|0.00|0.15|
|X|0.00|0.15|
|Y|**−0.18**|**0.42**|

*200 male samples*

|chromosome|avg. mean|avg. spread|
|---|---|---|
|1|0.00|0.13|
|X|0.00|0.13|
|Y|0.00|0.13|

*200 female samples*

|chromosome|avg. mean|avg. spread|
|---|---|---|
|1|0.00|0.17|
|X|0.00|0.17|
|Y|−0.79|0.45|

Note how avg. spread on chromosome Y is significantly higher for 200m+200f dataset (0.42) than in 200m dataset (0.13), while in theory they should be the same, seeing as chromosome Y data for female samples should be ignored. Mean (−0.18) is also not 0.00, as it should be.

I believe part of the problem might lie in [`if is_sample_female:`](https://github.com/etal/cnvkit/blob/master/cnvlib/reference.py#L88) branch of *cnvlib.reference.combine_probes.shift_sex_chroms*. It assigns a fixed coverage of −1.0 for every chrY bin in female samples. One can see how this skews the real distribution by adding a large number of values that aren't actually there. I tried changing −1.0 to seemingly more fitting `None` or `np.nan`, and it _did_ change the avg. mean on chrY for 200m+200f dataset to correct 0.00, but it did nothing to fix the spread. So probably there's something else going on there.

The possible real world consequence of this issue might be the loss of genuine chrY duplications, which would be dismissed as noise due to calculated spread being higher than it really is. (Deletions are unlikely to be missed this way.)

Please let me know if I could be of further assistance.

— Kirill

**Comment by tskir** [comment]
Here's the script that I used:
``` python
from random import gauss
from math import log
header = 'chromosome\tstart\tend\tgene\tlog2\n'
num_of_samples = 200
num_of_regions = 10


def random_cvg(chrom, sex):
    cvg = log(max(0.1, gauss(1, 0.1)), 2)
    if sex == 'm' and chrom == 'X':
        cvg -= 1
    if sex == 'f' and chrom == 'Y':
        cvg = -10
    return cvg


for sample in range(num_of_samples):
    for sex in 'm', 'f':
        with open('sim{}{}.target.cnn'.format(sex, sample), 'w') as output:
            output.write(header)
            for chrom in '1', 'X', 'Y':
                for region in range(num_of_regions):
                    left = (region + 1) * 1000
                    right = left + 500
                    cvg = random_cvg(chrom, sex)
                    output.write('chr{chrom}\t{left}\t{right}\tGENE{chrom}'
                                 '\t{cvg}\n'.format(**locals()))
        with open('sim{}{}.antitarget.cnn'.format(sex, sample), 'w') as output:
            output.write(header)
```

And here're the commands I ran:
``` bash
rm *.cnn
python generate_cnns.py
# Check that gender is detected correctly for each sample
cnvkit-0.7.11/cnvkit.py gender sim*.target.cnn
cnvkit-0.7.11/cnvkit.py reference -o ref.cnn sim*.cnn
```

For only male/female samples, I change `sim*.cnn` in the last command to `simm*.cnn` or `simf*.cnn`, accordingly.

**Comment by etal** [comment]
Thanks for exploring this and letting me know, I'll take a look.

**Comment by etal** [comment]
In the `random_cvg` function in your script, -1 should also be subtracted from the log2 coverage of chrY in male samples. I used this version to simulate samples:

    def random_cvg(chrom, sex):
        cvg = gauss(5, 0.15)
        if sex == 'm' and chrom in ('X', 'Y'):
            cvg -= 1
        elif sex == 'f' and chrom == 'Y':
            cvg -= 10
        return cvg

(The coverage depths in absolute scale are log-normal, so gauss is fine for simulating log2 values directly. I also wanted to test whether `reference` was centering the log2-scaled depths properly, hence the mean of 5.)

I generated 20 samples of each sex with 100 bins per chromosome using a modified version of your script (thanks!). Then I built "male" and "female" references from (1) all male and female samples together, (2) just male samples, and (3) just female samples. Here are the averages in each:

Female reference from all samples:

                    log2    spread
    chromosome                    
    1          -0.001506  0.157784
    X           0.001581  0.154590
    Y          -0.988280  0.117605

Male reference from all samples:

                    log2    spread
    chromosome                    
    1           0.003008  0.193789
    X          -0.973643  0.165425
    Y          -0.948668  0.098323

Female reference from female samples:

                    log2    spread
    chromosome                    
    1           0.002292  0.155977
    X          -0.001183  0.146241
    Y          -0.992678  0.067857

Male reference from female samples:

                    log2    spread
    chromosome                    
    1           0.004580  0.186917
    X          -0.982996  0.151739
    Y          -0.952042  0.016728

Female reference from male samples:

                    log2    spread
    chromosome                    
    1           0.000304  0.153561
    X           0.000208  0.151922
    Y          -0.986553  0.166322

Male reference from male samples:

                    log2    spread
    chromosome                    
    1           0.000700  0.193547
    X          -0.970695  0.167748
    Y          -0.980652  0.170771

The `log2` values are roughly where they should be. CNVkit correctly detected the genders of all simulated samples, as it ought to, since the Gaussian noise is reasonably low.

The Y-chromosome `spread` values are OK for the last 2 references (male samples only), but too low for the first two (mixed samples) and surprisingly nonzero for the middle two (female samples only).

- For a mixed-sex pool of samples, the spread is reduced because female samples' chrY log2 values are set to exactly -1.0 (to help log2 values behave well). But the spread should be higher than for autosomes because the sample size is smaller (female samples are not used for calculating spread).

- For a female-only pool of samples, the log2 values are indeed all set to -1.0 initially. But during the bias-correction step, these bins get pulled in and adjusted slightly. Since these values are not real observations they should not be used in the bias corrections.

It would be better to use `NA` for female samples's Y-chromosome log2 values in `reference.combine_probes`, and adapt the bias correction functions to handle `NA` values safely. Then, if only female samples were used in the pool, the pseudocount value of -1.0 will fill in for chrY, matching the generic/"flat" reference created when no samples are available.

**Comment by etal** [comment]
I tried a few alternatives, including masking out or interpolating NaN values in the `rolling_median` function. Basically, using NaN values for female chrY caused the output reference's log2 value to be shifted away from the expected -1, which is not good:

Female reference from all samples:

                    log2    spread
    chromosome                    
    1          -0.002072  0.140123
    X          -0.002261  0.166277
    Y          -0.951099  0.165485

Male reference from all samples:

                    log2    spread
    chromosome                    
    1          -0.123011  0.264189
    X          -1.050158  0.357280
    Y          -0.926985  0.199611

Female reference from female samples:

                    log2    spread
    chromosome                    
    1           0.004721  0.120857
    X          -0.004658  0.148182
    Y          -1.000000  0.000000

Male reference from female samples:

                    log2    spread
    chromosome                    
    1          -0.049559  0.322429
    X          -0.975730  0.391549
    Y          -1.472760  0.000000

Female reference from male samples:

                    log2    spread
    chromosome                    
    1          -0.007329  0.131228
    X           0.016613  0.164133
    Y          -0.989119  0.160136

Male reference from male samples:

                    log2    spread
    chromosome                    
    1          -0.123608  0.154918
    X          -0.992704  0.176640
    Y          -0.989849  0.186340

Using -1 keeps `log2` where it should be but shrinks `spread`. I think this is an acceptable tradeoff -- `log2` affects CNA calls directly, while `spread` is used to drop bad bins from the reference and calcualte bin weights, which are then used in segmentation, but only relative to surrounding bins, so a chromosome-wide bias only reduces the effectiveness of the weights in segmenting chrY and should not affect other chromosomes or otherwise mask true CNAs.
