### ISSUE TITLE
recs/tweaks for WGS

### ISSUE THREAD

**Issue by brentp** [etal/cnvkit#139]
I am able to run cnvkit on WGS data following the instructions

are there parameters that would be good to tweak or explore that would be likely to improve accuracy on WGS data?

**Comment by etal** [comment]
I should loop in @chapmanb -- I left a similar thread hanging a little while ago.

The source for the "batch" command in cnvlib/commands.py shows what I've changed when "--method wgs" is specified. Of interest:
- The sequencing-accessible regions calculated by `access` are used as targets. It's helpful to exclude the known problematic regions, especially when the number of normal/control samples is limited. In the source distribution you can use `data/access-5k-mappable.*.bed` with batch's `-g` option, but without that option it will use all long non-N regions in the genome's FASTA sequence. The sources for the data files are in https://github.com/etal/cnvkit-examples/tree/master/intervals.
- I haven't evaluated how the three segmentation algorithms perform on WGS. In particular, the `haar` method can return results that are similar to `cbs`, but it's much faster -- and could be sped up further. The `flasso` method is also faster than `cbs`, but there seems to be a bug in either my R script or the upstream package that causes it to crash when parallelized over chromosomes, and I'm not sure how its accuracy compares to CBS on WGS. I'm planning to implement the CODEX and Convading algorithms "soon" and I think they might perform better.
- The p-value or q-value threshold (`-t`) generally needs to be more stringent on WGS, probably because the log2 ratios mildly violate the segmentation methods' assumption of normality. The outlier filter stringency (`--drop-outliers`) is another parameter that could affect that, but a light touch seems best there.
- The `call` option `--filter` is new and could be the most useful for filtering out false positive calls. Try `segmetrics --ci --bootstrap 500`, then `call --filter ci` to calculate the confidence interval for each segment mean, then merge any segment where the CI crosses 0 with its neighbors. The `--filter cn` option can be used alongside `ci` on the same command line and will merge segments with the same absolute copy number after it's been called. Watch for bugs...

**Comment by brentp** [comment]
Thanks Eric, I'm not too worried about the speed at this point. We are running WGS germline samples (not cancer) and I wanted to make sure it's reasonable.

**Comment by etal** [comment]
I think the implementation in bcbio-nextgen should suit your needs fairly well, then. But the `--filter` part is new in both CNVkit and bcbio, so I'm interested to hear how it works for you if you try it out.

**Comment by brentp** [comment]
Hi Eric, I'm using this:

```
cnvkit() {
    set -euo pipefail
    bam=$1
    callable=$2
    sample=$3
    fasta=$ref # ref must be exported by caller
    cnvkit.py target $callable --split -o ${sample}.target.bed --avg-size 500
    cnvkit.py antitarget -g $callable ${sample}.target.bed -o ${sample}.antitarget.bed

    cnvkit.py coverage -p $threads $bam $sample.target.bed -o $sample.targetcoverage.cnn
    cnvkit.py coverage -p $threads $bam $sample.antitarget.bed -o $sample.antitarget.cnn

    cnvkit.py reference -f $fasta -o $sample.targetcoverage-flatbackground.cnn -t $sample.target.bed -a $sample.antitarget.bed
    cnvkit.py fix -o $sample.cnvkit.cnr $sample.targetcoverage.cnn $sample.antitarget.cnn $sample.targetcoverage-flatbackground.cnn
    unset R_HOME
    cnvkit.py segment -o $sample.cnvkit.cns.tmp $sample.cnvkit.cnr --threshold 0.00001
    cnvkit.py export seg -o $sample.cnvkit.cns $sample.cnvkit.cns.tmp

    rm  $sample.targetcoverage.cnn $sample.antitarget.cnn $sample.targetcoverage-flatbackground.cnn
}
```

Does that seem reasonable? It's obviously single-sample. Is there a multi-sample way to do this?

**Comment by etal** [comment]
That's pretty much it. I'm hearing some positive reports about running the .cns through `segmetrics --ci` and `call --filter ci`, so you might want to insert that before `export seg`.

To parallelize I use `make`, see:
- https://github.com/etal/cnvkit/blob/master/test/Makefile
- https://github.com/etal/cnvkit-examples/blob/master/Makefile

**Comment by brentp** [comment]
got it. thank you.
