### ISSUE TITLE
Support RNAseq via import-rna

### ISSUE THREAD

**Issue by etal** [etal/cnvkit#151]
Most genes' expression correlates reasonably well with genomic copy number.  Quantifying transcript expression is hard, but existing programs like [rsem](http://deweylab.github.io/RSEM/) and [salmon](https://combine-lab.github.io/salmon/) can do it efficiently.

*Task:* Implement `import-` sub-command(s) to convert the output table of a transcript quantification tool to CNVkit's .cnn or .cnr format.

- Some additional input may be needed to match the input tables (e.g. gene IDs) to genomic coordinates -- maybe take refFlat.txt or a BED file of gene coordinates.
- Exon-level values are preferred, but gene-level is also useful for detecting large-scale CNAs.
- The log2 value and perhaps weights can be computed from observed vs. expected read counts.

Should the output be .cnn or .cnr?
- For .cnn output:

    - GC and RepeatMasker corrections are then possible with `fix`, but I don't know yet whether they're worthwhile for these inputs.
    - `fix` expects a reference, but a useful RNAseq reference can't be constructed the same way as for DNAseq. Perhaps "log2" could be left flat and "spread" could be computed from a pool of RNAseq .cnn files for the purpose of filtering out non-housekeeping genes.

- For .cnr output: 

    - If GC and RepeatMasker corrections are useful, they'll need to be performed during import here. Samples will be normalized to themselves instead of to a reference.
    - Since expression levels vary wildly, some regional smoothing or outlier filtering may be needed (beyond the outlier filtering already in `segment`).

**Comment by JspSrs** [comment]
Hi Eric,

Seems a good goal to me. I have seen some effort into converting RNAseq data into copy number and doing reasonable well. From the groups of B IJlstra and/or L. Franke, I think.

Perhaps obvious - Depending of the type of library prep non-coding transcripts should be included in the Gene IDs file.

Regarding .cnn and .cnr – for a fixed reference file often large numbers are needed for the aggregate file. Intuitively and from a practical view I prefer an internal normalization, with  information of noise parameters in order to reject samples. From history, we used to have nice results using CNAG for Affymetrix genomic array arrays for copy number calling. CNAG was developed for cancer samples and uses on-the-fly selection of files to generate a tailored reference, based on array characteristics like total intensity, noise, dynamic range and intensity fluctuation across the SNP array surface.

M2c,
Best regards, Jasper

**Comment by etal** [comment]
Thanks for the pointers, Jasper, and sorry I missed this comment earlier.

I've looked through recent papers by Bauke Ylstra and Lude Franke but did not find any papers specifically describing CNV inference from RNA-seq alone. Is there a particular paper you have in mind?

If you're interested in trying this functionality in CNVkit, it's now available in the development version you can pull from GitHub. I've documented the usage of the new ``import-rna`` command here: http://cnvkit.readthedocs.io/en/latest/rna.html

Unlike the DNA-seq pipeline, ``import-rna`` normalizes a batch of samples together rather than using a fixed pool of normals. The ``metrics`` command should still be useful to identify noisy samples. (For DNA-seq, on-the-fly selection of a subset of samples for the reference is a work in progress, hopefully landing within the next few months.)
