### ISSUE TITLE
scatter: Set x-axis limits to match the specified range

### ISSUE THREAD

**Issue by gabeng** [etal/cnvkit#180]
I have been trying several options to modify the range using -g or -c in combination with -w. Changes in the x-axis range seem to appear only at certain steps, but certainly not as I specify. Any tips?
Why is the x-axis not exactly the range specified with -c?

**Comment by etal** [comment]
CNVkit lets matplotlib decide the x-axis, though I agree it would be an improvement for CNVkit to enforce the specified boundaries as x-axis limits.

The displayed region is the specified coordinates (`-c`) plus the window size (`-w`) in each direction, trimmed to the first datapoint inward from each side. The datapoints are bin midpoints, and CNVkit first selects the datapoints in the specified window and then asks matplotlib to display them as it sees fit. Since antitarget bins are sparse, the amount trimmed from the expected boundaries can be noticeable.

**Comment by gabeng** [comment]
Thanks for the explanation. I was trying to plot anything noticeable programmatically and ended up with strange results. In my view the trimming to the first datapoint inward does not make a lot of sense. Since my antitargets are very sparse (2mb), I am never able to provide a certain space around a gene of interest in the plots. It would be nice if that could be changed.
