### ISSUE TITLE
Bias correction shows boundary artifacts on small datasets

### ISSUE THREAD

**Issue by gabeng** [etal/cnvkit#181]
In a small set of 12 samples and a small single-gene amplicon panel I see 7+ bins in my reference with zero log2 and zero spread. How is that possible? Coverage is >400x. All samples have good coverage in these regions.

**Comment by gabeng** [comment]
When I change the coverage calc method to `-c` those zeros in the reference go away. I should note that most amplicons overlap. I can see that reads are counted twice in the debug output. This is reduced using the `--count` method, but the result from `--count` is also much noisier. Any thoughts or experience with amplicon based data?

**Comment by etal** [comment]
1. Did the targetcoverage.cnn files input to `reference` all or mostly have 0 depth at those sites? Or, did the depth values vary wildly there? Were all these 0-value bins completely overlapped by other bins? (I'm not sure if htslib bedcov allows double-counting sites.) Were these reads be marked as duplicates or secondary, in a repetitive region, or any other reason they might be skipped by default in htslib? In principle a log2 of 0 means neutral/average coverage depth, not zero coverage, but seeing 7+ bins with exactly 0 log2 and depth suggests the read depths for those bins were disqualified for some reason. Or maybe there could be a bug in `reference` or the re-centering method triggered by operating on just one chromosome.

2. Since you are using a reference of one or more normal samples, it might be better to run your amplicon intervals through `target` first to flatten out and re-subdivide the overlapping regions. Have you tried that? I don't have much direct experience with amplicon data, but several other CNVkit users have attempted it with at least some success.

**Comment by gabeng** [comment]
First your #2: I first merged all overlapping regions and then let `cnvkit` split them up. 

* All regions are well covered. Those regions with 0 spread/log2 have at least 800x in every sample (indicated by cnvkit) and those values vary only slightly, but they are not identical.
* The data is single end.
* Since I first merged overlapping regions in the bed file, there are no overlapping bins. 
* Reads were not marked as duplicates as recommended by vardict and bcbio for amplicon panels.
* Coverage calculation looks fine. All *.cnn files contain reasonable data for every single bin. Since this issue persists no matter which method of coverage calculation I choose, this is probably an issue downstream.
* I checked this with the current version from the master branch.

**Comment by gabeng** [comment]
I identified the cause: GC and edge corrections need to be turned off when creating the reference. The documentation should be updated. I appreciate your commends and questions, though. Made me think a little further.

**Comment by etal** [comment]
Thanks for investigating. Any corrections disabled for `reference` should also be disabled for `fix`, in general. For amplicon sequencing the edge correction wouldn't be expected to do anything useful, but the GC correction ought to work and should help, as I understand it. This looks like undesired behavior in the GC rolling-median correction, maybe pollution by NaNs somehow. If the same issue occurs with just one targetcoverage.cnn file, would you be able to send it to me so I can debug?

**Comment by gabeng** [comment]
Would be happy to provide you with data. What exactly should I do?

**Comment by etal** [comment]
Could you e-mail one of your input targetcoverage.cnn files to eric.talevich@ucsf.edu?

**Comment by etal** [comment]
I've replicated the issue. Usability note: if you don't provide `-f` it will skip the GC and RepeatMasker corrections automatically, so only `--no-edge` is needed in addition.
