### ISSUE TITLE
How to disable splitting of targets in batch?

### ISSUE THREAD

**Issue by kyleabeauchamp** [etal/cnvkit#185]
I recently upgraded to 0.8.3 and I'm finding it difficult to prevent `cnvkit.py batch` from rebuilding my target.bed with split regions.  I want to use batch to re-generate the reference, but leave my target and antitarget bed files untouched for reproducibility purposes.  

Is this something that I can control by matching the command line arguments exactly?

I then tried to follow the "manual reference" recipe but I think the docs might be outdated.  In particular, the following command suggests passing BAMs directly into `cnvkit.py reference` but the man pages say that the CNN profiles need to be constructed first:

```
# From https://cnvkit.readthedocs.io/en/stable/pipeline.html#batch

cnvkit.py reference *Normal.bam -t my_targets.bed -a my_antitargets.bed \
    [--fasta hg19.fa --male-reference] -o my_reference.cnn

[...]

# From the man page:
cnvkit.py reference -h 
usage: cnvkit.py reference [-h] [-f FASTA] [-o OUTPUT] [-y]
                           [-g {m,male,Male,f,female,Female}] [-t TARGETS]
                           [-a ANTITARGETS] [--no-gc] [--no-edge] [--no-rmask]
                           [references [references ...]]

positional arguments:
  references            Normal-sample target or antitarget .cnn files, or the
                        directory that contains them.

```

I'm now trying to decide whether I want to continue using batch or just run every step piecewise.

**Comment by etal** [comment]
Sorry, that's a mistake in the docs. It's the `batch` command that can take new BAMs and an existing reference or target/antitarget regions (which are always split now, to prevent user error), while `coverage` takes the target BED as given.

You can use `batch` with the existing reference to and new BAMs to generate (anti)targetcoverage.cnn files with matching interval coordinates; the old and new .cnn files will both work (even together) with the `reference` command in the updated CNVkit to build/update a new reference. Have you tried that? The `batch` command will then work as expected on new tumor/test samples with the given, rebuilt reference (`-r`).

    cnvkit.py batch *NewNormal.bam -r ref-orig.cnn
    cnvkit.py reference *coverage.cnn -o ref-new.cnn
    cnvkit.py batch *.bam -r ref-new.cnn 

I'm assuming this additional step doesn't take much time to perform. If there's more you need to do here and the procedure turns out to be gnarly, I can add a `--no-split` option.

**Comment by kyleabeauchamp** [comment]
Thanks!  I did not try the 3 step idea, I may try it if I revisit this later.  I ended up just calling the commands manually for extra control.
