### ISSUE TITLE
Segmenting single chromosome vs entire genome

### ISSUE THREAD

**Issue by gabeng** [etal/cnvkit#188]
I just noticed that it makes a great difference if I feed just chr1 to `cnvkit.py segment` compared to feeding it all data from the entire genomic region. I am working with noisy WES datasets. flasso seems to provide best performance - but only when I perform segmentation on chromosomes separately.
I created different datasets from the same `.cnr` using `head -n XXX`. It seems that the total number of segments drops when the number of lines in the `.cnr` exceeds around 45000. Any ideas?

**Comment by etal** [comment]
Thanks for reporting.

1. Does this happen with `-m haar`, too, or just `cbs` and `flasso`?
2. Are you specifically grabbing each chromosome (`grep chr1 foo.cnr > foo_chr1.cnr`), or a fixed number of lines that could be truncating a chromosome?

My understanding / intention was that the segmentation algorithm works on each chromosome independently, but the number of bins within each chromosome and their variance will affect how the algorithm estimates the level of noise in bin log2 values, so e.g. the isolated chromosome arm 1p would not be expected to segment identically to the whole chromosome 1. CBS in particular (Bioconductor package `DNAcopy`) samples the available datapoints in the given array to estimate distributions, and 45000 might be a hard-coded upper limit for an internal optimization.

**Comment by gabeng** [comment]
1. This does not affect `haar`, but unfortunatley, `haar` seems to be absolutely insensitive to the `threshold` parameter and it does not perform well with on my noisy data. 
2. I tried both. `chr1` is about 28k segments and segmentation works fine on that. Then I tried 30k, 40k, 45k, 50k lines from the `.cnr` file. The jump from 45k to 50k makes all the difference in the result. 

It looks like the `cbs` and `flasso` should be run on smaller sections of the genome or on chromosomes. Otherwise I miss the (clear but small) deletions in my data. Do you see similar effects on your WES data?

**Comment by etal** [comment]
So, the odd thing is that `cbs` already does operate on each chromosome separately. (But `flasso` does not, because it segfaults if I run it that way.) At 40k-50k lines, which I'm assuming truncates chr2, does the segmentation of chr1 change, or only chr2? How does chr1 look if you truncate it to ~14k lines? If that's better, I can look into segmenting each chromosome arm independently.

Maybe an R quirk could explain why `cbs` and `flasso` are behaving this way. I wonder if @HenrikBengtsson has seen this in PSCBS.

The `haar` issue sounds like a bug; from looking at the code I'm not sure why the q-value is being ignored.

CNVkit has seen the most action on UCSF's target panels with a total of about 30k bins for the genome, which doesn't hit the 45k limit you found. The exomes I've analyzed have been better-quality fresh-frozen tissue samples, not too noisy, so I wasn't unhappy with the results I got initially once I found a suitable `-t` value.

**Comment by HenrikBengtsson** [comment]
Hi, sorry, but rather swamped so don't have time to get into the details about this, but if you think it's related to DNAcopy, don't hesitate contacting Venkat (https://github.com/veseshan) directly.  He's a great guy and very helpful.

**Comment by gabeng** [comment]
Thanks for the link. I will contact Venkat.
