### ISSUE TITLE
targeted sequencing using pull down

### ISSUE THREAD

**Issue by leoSeattle** [etal/cnvkit#199]
Hi,
I have a set of targeted sequencing data (around 80 genes), and try to do CNV analysis using cnvkit. We didn't use amplicon approach, used pull down, and it worked very well. 

I cannot find an option for pull-down approach, I guess I can use "-m amplicon". But I got an error when I run following command as the documentation suggested:
$ cnvkit.py batch *.bam  -m amplicon -p 8  -t BedFile.bed
Options -n/--normal and -t/--targets (at least) must be given to build a new reference if -r/--reference is not used.
(See: cnvkit.py batch -h)

We have a set of normal samples (6 samples), and I used them to build a pooled reference, then, I estimated the CNV for each of those normal samples using the pooled reference. I found in some samples, there are many regions have gained or lost copy number. Also the variation across regions is big. Could you tell me what I can do? 

When I run cnvkit.pl fix with default. I got a warning that no-gc correction. How to turn it on?

Thanks

Leo

**Comment by etal** [comment]
Hi Leo,
Pull down is also called hybrid capture. This is the default in CNVkit, and can be specified explicitly with the `-m hybrid` option. I suggest a command line like:

    $ cnvkit.py batch *Tumor.bam -n *Normal.bam -f genome.fasta -p -t BedFile.bed -m hybrid

(Option order doesn't matter.)

Note:
- To get GC correction, you need to specify the reference genome sequence in FASTA format using the `-f` option.
- Give all of your normal sample BAM filenames after the `-n` option to build a pooled reference.
- If you specify `-m hybrid` instead of `-m amplicon`, there may be fewer spurious CNAs in your normal samples. Some might remain; the method isn't perfect. You can use the `metrics` command to determine if any of your normal samples have significantly noisier coverage than the rest, and maybe not include those in the pooled reference.

**Comment by leoSeattle** [comment]
Thanks for the quick response. After post my question, I realized that my "pull-down" might be the default "hybrid" approach, someone should make standards for those biotech terms.

Here is the results I got using metrics. How can I tell which one I should remove?
sample  segments        stdev   mad     iqr     bivar
ref1.targetcoverage.cnn  49      1.01704 0.618513        0.870118        0.62546
ref2.targetcoverage.cnn  49      1.35179 0.586778        0.813928        0.579714
ref3.targetcoverage.cnn  49      1.43868 0.577375        0.779971        0.540559
ref4.targetcoverage.cnn  49      1.38549 0.583706        0.876727        0.640025
ref5.targetcoverage.cnn 49      0.822916        0.797854        1.08827 0.725094
ref6.targetcoverage.cnn 49      0.625802        0.47389 0.644826        0.455212

**Comment by etal** [comment]
Those all look OK to me. A bad sample will usually have distinctly higher values in the latter 4 columns, e.g. `bivar` above 1.0. But it is a judgement call, and if you see a bad sample you should probably look at the other upstream QC metrics to see what went wrong, e.g. low sequencing coverage, insert size, input DNA mount, etc. The numbers look better in the .cnr files after normalization and GC correction.
