### ISSUE TITLE
Some genes from refFlat not in .cns file

### ISSUE THREAD

**Issue by danielbruhm** [etal/cnvkit#205]
In my refFlat file I have the following entry:
CXCL10	NM_001565	chr4	-	76942268	76944689	76943082	76944584	4	76942268,76943518,76943843,76944523,	76943101,76943608,76943970,76944689,

In the .cns file generate by CNVkit I have the following segment:
chr4    70599086        106551509

In the .cns file many genes that fall within this segment are listed, but not CXCL10 - wondering why this is?

Thanks

**Comment by etal** [comment]
Was CXCL10 in your target panel? If it's not an annotated target (i.e. in targets.bed), then it won't be carried over into the .cnr and .cns files.

**Comment by danielbruhm** [comment]
CXCL10 was in my target panel and I just double checked that it was within the coordinates in my targets.bed file.  It looks like CXCL10 which is transcribed from the - strand is actually overlapping another gene, ART3, which is transcribed from the + strand in the hg19 reference genome, and within the targetcoverage.cnn file the bins that contain CXCL10 and ART3 are only labeled as ART3.  Seems to be the case for some other genes, e.g. IFNK and MOB3B are overlapping and transcribed from different strands and in the targetcoverage.cnn file these bins are just labeled as MOB3B, also IFNE is within MIR31HG on the same strand and is only labeled as IFNE.  Might be useful for some people to list all genes overlapping a bin.  I was just looking to extract a few genes by gene name in the segmentation file but I can just do that by coordinates.

**Comment by etal** [comment]
I see. Which version of CNVkit are you using? The annotation behavior might be better in the most recent version, 0.8.5.

If you're already on v0.8.5, or even with 0.8.4 and maybe a few versions earlier, then you can re-annotate the bins in your .cnn, .cnr and .cns files without re-running the `coverage` or `batch` command. To extract the gene annotations and retain overlapping genes, use this bundled script:

    refFlat2bed.py refFlat.txt -f -o refflat-genes.bed

From there you can either re-run your pipeline using `refflat-genes.bed` instead of the original `refFlat.txt` as your `--annotate` argument, or use `cnvlib` in a Python script to transfer the annotations to your .cnr and .cns files and rewrite them:

    import cnvlib
    cn = cnvlib.read("mysample.cnr")
    refflat = cnvlib.tabio.read_auto("refflat-genes.bed")
    cn["gene"] = refflat.into_ranges(cn, "gene", "-")
    cnvlib.tabio.write(cn_table, "mysample.newgenes.cnr")

**Comment by danielbruhm** [comment]
I'm using v0.8.3 right now -- ^ that's exactly what I need though , thanks a lot!
