### ISSUE TITLE
the scatter plot is very weird

### ISSUE THREAD

**Issue by leoSeattle** [etal/cnvkit#206]
The bar should be in the middle of points, why it is way below the middle?
[3S12-075080FM_S3_sorted_mkDup_sorted2-scatter.pdf](https://github.com/etal/cnvkit/files/836125/3S12-075080FM_S3_sorted_mkDup_sorted2-scatter.pdf)

**Comment by etal** [comment]
There are probably a lot of bins with no or low coverage depth. Did you run with `--drop-low-coverage`?

You can fix this shift in the .cns files with `cnvkit.py call -m none --center biweight` or `--center median`.

**Comment by leoSeattle** [comment]
I did use the "--drop-low-coverage", the whole command is:
 cnvkit.py batch *sorted2.bam -n  ~/*.bam  -f ~/resource/hg19/hg19.fa -p -t ~/bed/TargetFrom3Tube_sorted.bed -m hybrid  --access ~/software/cnvkit/cnvki
t-master/data/access-5k-mappable.hg19.bed --output-reference  my_reference.cnn --output-dir cnvkit_out  --drop-low-coverage

my question is: 
1: why "--drop-low-coverage" not working? because I am using the batch model?
2: how to avoid "a lot of bins with no or low coverage depth", besides "--drop-low-coverage" option or how to make "--drop-low-coverage"?

**Comment by etal** [comment]
The `--drop-low-coverage` option presumably is working; you'll see log messages like "Dropped N low-coverage bins" during segmentation.

The basic problem is that you have poor sequencing coverage resulting in overall noisy data and in particular a lot of target bins with very low coverage depth. This could be due to an inefficient capture, degraded samples, low input DNA amount -- a number of QC issues that can be flagged after library preparation and sequencing. You can try to address this in CNVkit by using larger bin sizes (see the script `coverage_bin_size.py` or the v0.8.5 command `autobin`), and by double-checking that you've used the right set of targets and that all of the normal-sample BAMs used in your pooled reference were prepped according to the same protocol as your tumor sample.

Math: The log2 ratios are not really normally distributed, and will skew low especially when the coverage depth is low. Segmentation finds the breakpoints, which is the important part, and then takes the weighted mean of bin log2 values within each segment to compute the segment's log2 value. Due to the skew this segment mean will be below the median and mode, i.e. where most of the datapoints appear to cluster and where the bin log2 values were initially centered. If the segment breakpoints are OK then you can re-center the segments with `call --center` and the resulting segment log2 values will be about where they should be if the copy number signal is detectable. But if the data are too noisy, if you can't tell visually where the larger CNAs are from the gray dots in the scatter plot, then the breakpoints may also be wrong and you should look further upstream in your pipeline.

**Comment by leoSeattle** [comment]
Thank you very much.

Here is another unrelated questions. Say I have 10 normal samples, which of following approaches is better or they are same:
1: combine them together to have one set, and generate one reference for CNV detection.
2: divide them to two sets, and generate two references, finally, there will be two sets of detected CNVs for a tumor sample, select the overlapping CNV as the final one.

**Comment by etal** [comment]
If there's a clear difference between the two sets of normals, you could try two separate pooled references. Otherwise I'd go with `cnvkit.py segmetrics --ci` and `cnvkit.py call --filter ci` to remove likely false positives.

You can also try a flat reference (`-n` with no normal BAMs) for comparison if you're unsure about the suitability of the normals.

**Comment by leoSeattle** [comment]
The normal samples are expected to have no big difference among them. 
My concern is that there is no statistical significance for the reported copy number from cnvkit. So I thought the consistent results from two sets of normal references will give us more confidence.
Anyway, thanks for your suggestion, I will try that.
