### ISSUE TITLE
Error when I do not specify an access file

### ISSUE THREAD

**Issue by sbbundho** [etal/cnvkit#207]
Hello, 

I was trying to use your tool to generate a bed file for antitarget regions using the following command: 

python cnvkit/cnvkit.py antitarget /PATH/TO/BED/FILE/my_bedtargets.bed -o my_antitarget.bed

However, I am running into the following error:

Detected file format: bed
Traceback (most recent call last):
  File "cnvkit/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/u/sbundhoo/cnvkit/cnvlib/commands.py", line 282, in _cmd_antitarget
    access = tabio.read_auto(args.access)
  File "/u/sbundhoo/cnvkit/skgenome/tabio/__init__.py", line 104, in read_auto
    % infile)
ValueError: Can only auto-detect format from filename or seekable (local, on-disk) files, which None is not

When I ran the same command and specify an access file, I do not get this error. 

Isn't -g/--access supposed to be an optional argument?  How do I generate an antitarget BED file with all antitarget regions, including inaccessible regions? 

thanks, 

Shaheen

**Comment by etal** [comment]
You can generate this file with the `access` command using your reference genome sequence. This masks out the sequencing-inaccessible regions that would not have any mapped reads. The `batch` command is supposed to generate this on the fly if it's not provided on the command line, but I see I missed a spot.

To generate an "access" file that covers the whole chromosomes, you can manually create a BED file listing each chromosome name, 0 as the start position, and the chromosome length as the end position. But it's better to use the `access` command because the masked-out regions do not provide a good copy number signal for CNVkit.

I see you're using the development version, so you'll have access to the proper fix soon.
