### ISSUE TITLE
--vcf option to call no longer outputs BAF information, additional parameters are needed

### ISSUE THREAD

**Issue by rbatorsky-claritas** [etal/cnvkit#224]
The updated version v0.8.5 doesn't output baf,cn1,cn2 fields (header is also missing) when the --vcf option is passed to "cnvkit.py call". I've looked in the commands.py and see that if I add the options --sample-id and --normal-id the baf output is produced. Could you clarify that it works as expected and add this to the documentation? Also, could you clarify how cn1 and cn2 are calculated?

**Comment by etal** [comment]
Thanks for reporting. I'm looking into it.

The cn1 and cn2 values are calculated the same as in PSCBS: multiply the absolute integer copy number (`cn`) by the BAF and 1-BAF. CNVkit takes the higher value as `cn1`, and the lower as `cn2`.

**Comment by etal** [comment]
As a side effect of etal/cnvkit#218, it looks like the "baf" calculation is being skipped if the VCF is from tumor-only calling, or if the paired normal is not found automatically.

Working on a fix. But also see if you can add a PEDIGREE tag to your VCF, or otherwise help CNVkit automatically detect that it represents a tumor-normal pair. As it is, it looks like CNVkit needs "--normal-id" to find the matched normal sample in your VCF.
