### ISSUE TITLE
Pseudoautosomal Regions and Gender Inference in Reference

### ISSUE THREAD

**Issue by charliecurnin** [etal/cnvkit#234]
Thanks for making such a great tool!

I ran `coverage` on 169 samples. 81 were male; 88 were female. 

I then ran `reference` over the `.cnn` files, but the distribution of genders assumed was far from what I was expecting. Only 43 `.targetcoverage.cnn` and `.antitargetcoverage.cnn` files were assumed male, when 162 should have been. (EDIT: 43 is not the right figure, but I can't figure out what it was.)

I looked through several `.targetcoverage.cnn` files and discovered two discrete regions in chromosome Y where the depth was exactly 0. The coordinates of these regions overlap almost very closely (within a few hundred thousand base pairs) with PAR1 and PAR2, the two pseudoautosomal regions, on chromosome Y. 

I assume this is an issue with my BAM files—that no reads were aligned in these regions—but I'm wondering what I should do. Should I cut out all the lines where depth is 0? 

[Here](https://gist.github.com/charliecurnin/1dcef91abef2db0a5780644706e34f39) is a `targetcoverage.cnn` file (and its matching `antitargetcoverage.cnn` file) where the issue is visible. 

Thanks for your help.

**Comment by etal** [comment]
Sorry for the trouble, and thanks for sharing an example. Were the `.antitargetcoverage.cnn` or `.targetcoverage.cnn` files called more accurately, or did both have the sex mis-called about equally often?

The quick fix is probably to mask out those two pseudoautosomal regions from your accessible regions BED file (`access -x`). Could you share the coordinates of the problematic regions? I can add them to the `data/` folder as a BED file to be used this way (for other users, as well).

Alternatively, you could use the option `reference -x` to construct one or two references from all-male and/or all-female samples. It's a bit more annoying to manage two references, but this way `reference` is guaranteed to do as you ask, rather than attempting to infer chromosomal sex. You can re-use the existing sample .cnn files, and be sure to use the `-x` flag for all downstream sub-commands in your analysis.

**Comment by charliecurnin** [comment]
Thanks for the quick response! 

Actually, the `.antitargetcoverage.cnn` files are called perfectly. You mean masking out the problematic regions to get a new BED file, then redoing the `coverage` again? I don't quite have the computational resources for that—do you think I can just remove the problematic lines from the `.targetcoverage.cnn` files I have? 

I'd also rather not sacrifice statistical power by using only male or female samples for a specific reference, if possible. (I'm also very afraid I'll forget to use `-x`.)

Wikipedia gives the pseudoautosomal regions as 
```
The locations of the PARs within GRCh38 are:
Name	Chromosome	Basepair start	Basepair stop	Band
PAR1	X	10,001	2,781,479	Xp22
                Y	10,001	2,781,479	Yp11
PAR2	X	155,701,383	156,030,895	Xq28
                Y	56,887,903	57,217,415	Yq12

The locations of the PARs within GRCh37 are:
Name	Chromosome	Basepair start	Basepair stop
PAR1	X	60,001	2,699,520
                Y	10,001	2,649,520
PAR2	X	154,931,044	155,260,560
                Y	59,034,050	59,363,566
```

I'm using GRCh37, and what I've seen in my `.cnn` files is a gaps at around `(150853,2848034)` and `(59106538, 59343080)`.

**Comment by etal** [comment]
Sure, if the antitargets were called correctly then just deleting those rows from all .targetcoverage.cnn files should do exactly what you want.

**Comment by charliecurnin** [comment]
OK, so I guess I closed this prematurely. I tried what we discussed, deleting all rows in `(15083, 2848034) U (25365837,59343080)`. (I extended the second region slightly at the start because of poor coverage. My `.cnn`s jump from 28134216 to 59106538 so it's not as much as it seems.)

***And the quality of the gender inference actually went down. Zero target coverage samples were assumed male.***

The genders of the `.antitargetcoverage.cnn` files (which I cut nothing out from since their genders were inferred fine) continued to be inferred correctly. But whereas before at least *a few* target coverage samples were assumed (correctly) to be male, now none are. 

I have no idea how the `maleness` scoring is done. Many of the male antitarget samples have `maleness`s above 1000, but the highest in the target samples seems to be around .3. 

In the `.targetcoverage.cnn`s, chromosome Y does look a little sparse. It now covers only `(3447284,59343080)` with some gaps. (`(2848034,3447284)` is not available.) It's around 513 lines. But in much of it, the coverage is good! So could the issue be just that there's not enough chromosome Y for the `maleness` score to be high enough?

**Comment by charliecurnin** [comment]
Also, is there some place I can find more information and/or examples of how `reference -x` is used? It's not analogous to `reference -y`, right? It doesn't just create a female reference?

Do I give it only samples of one gender? How do I indicate the gender the samples are? And how can I set the gender for the reference I want (or is it still, by default, female unless I use `-y`)?

**Comment by etal** [comment]
The `-y` flag states that the output reference should be male (1 X, 1 Y). With it, female input samples' X chromosome log2 coverage is automatically halved, while male samples are left alone; without it, the opposite happens, so male samples' X chromosome log2 coverage is doubled and female samples are left alone.

The `-x` flag declares the input samples' known chromosomal sex, male (m/y) or female (f/x). Otherwise CNVkit will guess for each sample.

The automatic inference allows you to mix male and female samples in the input. The `-x` option exists so you can disable the automatic inference, but then you need to enforce the X/Y consistency yourself by providing only male or female samples, and telling CNVkit which one.

(It sounds like the inference method needs some tuning to keep extreme Y coverage values from overwhelming the other parts of the calculation.)

**Comment by charliecurnin** [comment]
Got it. Thank you. 

Ended up going into `reference.py` and preempting `cnarr.guess_xx()`.
