### ISSUE TITLE
unable to run CNVkit through DNAnexus

### ISSUE THREAD

**Issue by stacyhung** [etal/cnvkit#236]
Hi,

I would like to give CNVkit a try, but have not been able to run an analysis successfully.  In the DNAnexus wrapper environment, I have the following inputs:

Tumor sample mapped reads (BAM) (tumor_bams): GE0119B.bam
Normal sample mapped reads (BAM) (normal_bams): GE0119-N.bam
Baited regions (baits): Capture_V2.bed
Reference genome (FASTA) (fasta): ucsc_hg19.fa.gz
Male reference? (is_male_normal): false
Drop low-coverage bins? (drop_low_coverage): true

I am actually getting the same error regardless of the inputs for reference genome (with/without), male reference (true/false), and drop_low_coverage (true/false).

The error I am receiving is:

`CalledProcessError: Command 'dx-docker run -v /home/dnanexus:/workdir -w /workdir etal/cnvkit:0.8.3 cnvkit.py gender -o gender.csv GE0119B.cnr' returned non-zero exit status 1`

My guess is the error is related to a step in CNV that accounts for gender-specific qualities, but I don't see why that should come up since there's no requirement to have X and/or Y chromosomes (as far as I understand).

Can someone please assist?

Thank you,
Stacy

**Comment by etal** [comment]
Could you look a little further up in the DNAnexus job log to see if there's a full Python traceback? If it's there, could you copy it here?

**Comment by stacyhung** [comment]
Here's the python traceback:

**Comment by stacyhung** [comment]
Actually, there's some additional traceback that might be useful for debugging:

Traceback (most recent call last):
  File "/usr/local/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/commands.py", line 1391, in _cmd_gender
    table = do_gender(cnarrs, args.male_reference)
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/commands.py", line 1412, in do_gender
    return pd.DataFrame.from_records(rows, columns=columns)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 981, in from_records
    first_row = next(data)
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/commands.py", line 1410, in <genexpr>
    rows = (guess_and_format(cna) for cna in cnarrs)
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/commands.py", line 1406, in guess_and_format
    ("Female", "Male")[is_xy],
TypeError: tuple indices must be integers, not NoneType
Not file: /home/dnanexus/etal/cnvkit:0.8.3
Not file: /home/dnanexus/cnvkit.py
Not file: /home/dnanexus/gender.csv
File: /home/dnanexus/GE0119B.cnr
Traceback (most recent call last):
  File "/home/dnanexus/job-F5xppx80QfKY1Jvf4kzQ1GKb", line 21, in <module>
    execfile(_code_filename)
  File "/home/dnanexus/job-F5xppx80QfKY1Jvf4kzQ1GKb.code.py", line 241, in <module>
    dxpy.run()
  File "/usr/share/dnanexus/lib/python2.7/site-packages/dxpy/utils/exec_utils.py", line 150, in run
    result = ENTRY_POINT_TABLE[job['function']](**job['input'])
  File "/home/dnanexus/job-F5xppx80QfKY1Jvf4kzQ1GKb.code.py", line 45, in main
    target_avg_size, do_parallel)
  File "/home/dnanexus/job-F5xppx80QfKY1Jvf4kzQ1GKb.code.py", line 128, in run_cnvkit
    cnvkit_docker("gender", yflag, "-o", genders, *all_cnr)
  File "/home/dnanexus/job-F5xppx80QfKY1Jvf4kzQ1GKb.code.py", line 236, in cnvkit_docker
    sh(*(docker_prefix + list(args)))
  File "/home/dnanexus/job-F5xppx80QfKY1Jvf4kzQ1GKb.code.py", line 212, in sh
    raise exc
subprocess.CalledProcessError: Command 'dx-docker run -v /home/dnanexus:/workdir -w /workdir etal/cnvkit:0.8.3 cnvkit.py gender -y -o gender.csv GE0119B.cnr' returned non-zero exit status 1

**Comment by etal** [comment]
Sorry for the trouble. The underlying bug is fixed in the development of CNVkit, if you're able to run it locally.

CNVkit doesn't require a chromosome X or Y in general, but the `gender` command (now called `sex`) looks for at least one of those chromosomes to be present in order to infer the sample's chromosomal sex. Normally if you don't care about the sex chromosomes you wouldn't run that command, but the DNAnexus app does it as an extra step that was meant to be helpful, but in this case is unhelpful.

A workaround for the DNAnexus app issue would be to add a fake "X" chromosome with a small bin to your capture BED file, e.g. `chrX    100    1000`. When you re-run the app with this modified BED, the coverage in this faked target region will be too low for CNVkit to keep it as a target bin, but just having X listed among your targeted chromosomes will tell CNVkit to create antitarget bins across the whole chromosome and (assuming you've done hybrid capture) these will allow the `gender` command in the DNAnexus app script to complete without an error.

**Comment by etal** [comment]
I've updated the CNVkit app on DNAnexus to version 0.9.0, where this issue is fixed. Please let me know if this updated app doesn't work on your dataset.
