### ISSUE TITLE
Overlapping segments

### ISSUE THREAD

**Issue by kumarRBK** [etal/cnvkit#275]
Hi guys, I need your valuable help. After running CNVKIT gain-loss function by setting CN cutoff of 0.6 in the segmentation file, GISTIC showing following error message "1472 segment overlaps detected in the file, First overlap detected between segments at lines 9888 and 9889". Your help is highly appreciated. Thank you very much in advance.

**Comment by etal** [comment]
(Via chapmanb/bcbio-nextgen#2127 -- this is an "issue with segmentation", not a ["segmentation fault"](https://en.wikipedia.org/wiki/Segmentation_fault).)

Could you show how you generated these segments?

**Comment by kumarRBK** [comment]
@etal Thanks for your immediate reply.
I generated segment file using this command "cnvkit.py export seg sample.cns -o sample.seg" then I used CNVKIT gainloss function to filter CN by setting 0.6 as a cutoff(cnvkit.py gainloss sample.cnr -s sample.cns -t 0.6 -m 5 -y >sample_0.6cutoffgainloss.txt). Thanks.

**Comment by etal** [comment]
1. Inspecting the .cns file itself, do the segment boundaries in fact overlap? i.e. within each chromosome, the different between each segment's end position and the next segment's start position should always be 0 or greater, never negative.
2. If the segments overlap, it's probably because the input targets overlapped and were not flattened/merged properly with `cnvkit.py target` in a pipeline. I think bcbio-nextgen does this properly by default, but if question 1 shows overlapping segments, then you should check your input targets/baits BED file to see if those regions also contain some overlaps.

If the .cns file does not contain overlaps, then the SEG file shouldn't, either. GISTIC isn't formally supported by CNVkit and I haven't tested this workflow myself, so there might be some additional expectations GISTIC has that are not met by these SEG files. If you can find the issue, please let me know and I'll try to make the necessary change in CNVkit.

**Comment by kumarRBK** [comment]
@etal  Thank you so much for your suggestions. I will try and let you know if I get any positive result. Thank you once again.

**Comment by etal** [comment]
Relevant thread on GISTIC usage: #152

**Comment by hanico888** [comment]
Dear GISTIC users.
Im beginner to GISTIC, and I have overlapped issues in CNVanalysis using GISTIC online, my file is a CNV of Colon cancer from TCGA.  

this is a few lines of error:
Warning: Shortened 60 segments in '/opt/gpcloud/gp_home/users/Hanico88/uploads/tmp/run4785456974432728835.tmp/seg.file/1/111.txt' that overlap by one marker.
[> In make_D_from_segseq_data at 122
  In run_gistic2_from_seg at 193
  In gp_gistic2_from_seg at 97]

would you please help me resolve the issue?
