### ISSUE TITLE
What are the step for germline analysis?

### ISSUE THREAD

**Issue by bishwaG** [etal/cnvkit#296]
I did not get very clear picture (from the manual) how to perform analysis only on germline samples. Could you please list the step to call CNAs only from germline samples? Thank you very much in advance.

**Comment by etal** [comment]
Consider your germline samples as "test" and "control" instead of "tumor" and "normal". Then everything is the same. (Don't use the `--drop-low-coverage` option, though.) You can read the documentation for the [reference command](https://cnvkit.readthedocs.io/en/stable/pipeline.html#reference) to decide how to build a suitable pooled or flat reference.
