### ISSUE TITLE
It seems odd to set "rlibpath" instead of Rscript

### ISSUE THREAD

**Issue by MajoroMask** [etal/cnvkit#322]
This thought comes from my experience and issue #317. 

As far as I know, R manage its "libraries" (called packages in R) base on which R you been calling, since different versions of R have different versions of packages. If one uses Conda to set up an environment especially for CNVkit like this: 

`$ which conda`
`~/conda/bin/conda`
`$ which Rscript # default Rscript`
`/usr/bin/Rscript`

`$ conda create --name py27 python=2.7`
`$ source activate py27`
`$ conda install R`
`$ conda install cnvkit`
`$ source deactivate py27`

Then call R from this environment and install cnvkit dependencies: 

`$ ~/conda/envs/py27/bin/R`
`> source("http://bioconductor.org/biocLite.R")`
`> biocLite(c("DNAcopy", "cghFLasso"))`

If one wants to call `cnvkit segment`, the `~/conda/envs/py27/bin/Rscript` should be called instead of `/usr/bin/Rscript` under this situation. 

As I showed in pull request #321, after changing `Rscript`, one can call `cnvkit.py batch` or `cnvkit.py segment` with correct R libraries. 

Hope I made myself clear. As a conclusion, make a `--Rscript` argument replacing the `--rlibpath` should be more flexible.

**Comment by etal** [comment]
Thanks for investigating this. The `--rlibpath` option was introduced to help configure bcbio-nextgen pipelines, so I'd like to get @chapmanb 's input.

**Comment by etal** [comment]
Thanks for the tips, Brad. It sounds like it's technically possible to manage the R-related paths entirely through environmental variables, just potentially tricky for users.

I'm tempted to leave `--rlibpath` where it is, because I think other groups are using it now, and then also add an option `--rscript` to specify the absolute path to the intended Rscript. I'll also document how to use envvars to accomplish the same.

**Comment by etal** [comment]
The ``--rscriptpath`` option is in place now, if anyone would like to try it out. Thanks @MajoroMask and @chapmanb for the help and examples.
