### ISSUE TITLE
it is suitable for somatic CNV calling with tumor sample only without  normal ?

### ISSUE THREAD

**Issue by WinterLi1993** [etal/cnvkit#338]
HI,
    I just have tumor only sample ,without normal. 
    my data is  from  target panel  sequencing data . 
    tumor sample type is tissue or cfDNA .
    I am not sure  cnvkit is whether suitable for tumor only  somatic calling.

**Comment by etal** [comment]
Yes, CNVkit will work for this use case. Be careful that there will be some noisy genomic regions in your results, and consider using `segmetrics --ci` and `call --filter ci` to filter out poorly supported segments:
http://cnvkit.readthedocs.io/en/stable/calling.html

**Comment by vymao** [comment]
Just to clarify, will this be for germline or somatic CNV calling, or both? It seems like you would get a mixture of both if you just used the tumor-only mode.

**Comment by etal** [comment]
This approach would work for either germline or somatic CNV calling, but I've mainly used it for somatic. You can use additional parameters with `call` that are appropriate for either germline or somatic, depending on your own use case.

**Comment by etal** [comment]
Yes, you'd pick up both large-scale somatic and germline alterations. However, large-scale, functionally consequential germline alterations outside of repetitive regions are rare in healthy adults. For diagnostic purposes in pediatric cases, a clinician should also check for pathogenic germline alterations (of all types).

For the more common types of germline alterations, CNVkit is generally either unable to detect them because they are in repetitive or sequencing-inaccessible regions which are normally masked out, or they are smaller-scale than the somatic alterations and you'd be picking them up with `bintest` instead of CBS segmentation. They would look like fully clonal and likely non-pathogenic copy number alterations.
