### ISSUE TITLE
Heatmap

### ISSUE THREAD

**Issue by JImenaParedes** [etal/cnvkit#357]
Hello
I was wondering if I can group the data in the heatmap with a clustering or dendrogram. I want to determine if the samples have some kind of pattern or form groups.

Thank you in advance
Jimena

**Comment by etal** [comment]
A couple options:
- The heatmap will display the samples vertically in the order that you give the .cns files on the command line. So, if you have determined the groups separately, you can list the samples in the intended order of display, then save the plot as PDF (`-o myplot.pdf`) and edit it in Inkscape or Illustrator to add group annotations however you like.
- To perform clustering using the log2 ratios, you can export the sample .cnr files to Java TreeView or CDT format (`cnvkit.py export cdt` or `export jtv`), then load the output in Java TreeView to perform clustering there. That should give you a dendrogram and bin-level heatmap. (Clustering segments is a trickier problem because the segments don't match up precisely across samples.)
