### ISSUE TITLE
cnvkit.py scatter diagram heatmap commands and gender type

### ISSUE THREAD

**Issue by andyjslee** [etal/cnvkit#359]
I specified the --male-reference and --gender Male for the reference command on the samples that I know for sure are from male patients.

When I run the scatter, diagram and heatmap commands on those samples, I get the following log messages:
Treating sample 1 as female
Treating sample 2 as male

In fact there are more logs that identify the sample as female than male. Is this correct? All of my sequencing data are from male patients.

**Comment by etal** [comment]
The option `--male-reference` is there to mimic array CGH data, not to indicate the sex of the samples you used to construct your reference profile. In the current version this option has been renamed `--haploid-x-reference` to better indicate what it does and discourage people from using it.
https://cnvkit.readthedocs.io/en/stable/sex.html

If you've used `--male-reference` or `--haploid-x-reference` with the `reference` command, then you'll need to use the same option with every other command that supports it. Otherwise the inferred sex might be off.
