### ISSUE TITLE
Bug with the cnvkit install

### ISSUE THREAD

**Issue by AliceChoury** [etal/cnvkit#361]
Hi every body, 

I'm trying to install cnvkit in my new lab (and on my new PC) 

I installed python 2.7 and pip.

Now I run the command : `pip2.7 install cnvkit`
And I have this error...

```
copying pandas/tests/io/data/testdtype.xls -> build/lib.linux-x86_64-2.7/pandas/tests/io/data
    copying pandas/tests/io/data/stata6_117.dta -> build/lib.linux-x86_64-2.7/pandas/tests/io/data
    error: can't copy 'pandas/tests/io/data/legacy_msgpack': doesn't exist or not a regular file

    ----------------------------------------
Command "/usr/local/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-dd2j5C/pandas/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-sOcglQ/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-dd2j5C/pandas/
```

Can you help me please ?

**Comment by etal** [comment]
It looks like you don't have all the system dependencies installed. The numpy/scipy/pandas stack requires some system libraries that need to be installed through apt, not pip, on Linux.

I recommend using conda to do the installation, if you can. Those packages are pre-compiled with the necessary libraries.

Otherwise, you can see the CNVkit source code for creating the Docker image on a recent Ubuntu distro:
https://github.com/etal/cnvkit/blob/master/docker/Dockerfile
