### ISSUE TITLE
antitarget function

### ISSUE THREAD

**Issue by gooday23** [etal/cnvkit#37]
Hi Etal,

Thank you for developing CNVkit. It's brilliant!

I performed CNVkit on a small gene panel sequencing data, the result is very good.

However, I noticed that there are two chromosomes missing in the plot. These two chromosomes are missing in target or antitarget bed files too. Then I found the reason is I don't have any target designed for sequencing on these two chromosomes.

Since off-target reads should be all over the genome, I am wondering if this is a bug?

Looking forward to your reply.
Thanks ~

Hannah

**Comment by etal** [comment]
Good point. It makes sense to include the chromosomes that were not targeted if a significant number of off-target reads were mapped there.

Since CNVkit is designed to work with any reference genome, it's a little unclear how to select the relevant chromosomes for display (chr1-chr22, chrX, maybe chrY) but exclude chrM and the unassigned or alternative contigs in the reference sequence set. So, by default, CNVkit runs on the chromosomes that were targeted, and skips the rest.

I'll look into ways to make this behave better.

**Comment by gooday23** [comment]
Thank you!

**Comment by etal** [comment]
Quick workaround: Add a tiny region to your targets.bed file on each of the missing chromosomes in regions you don't care about, e.g. the first sequencing-accessible base of the chromosome. It will be thrown out of the reference for having low coverage (since it's not selectively captured), but CNVkit will then know to place antitarget bins over the rest of this chromosome.

**Comment by gooday23** [comment]
That's a smart solution! Thanks, I will have a try:)

-------- Original message --------

**Comment by kyleabeauchamp** [comment]
Hmm, I will say that I was a bit confused by the new behavior in 0.7.7 where chrY is dropped by default if there are no targets on it.  I personally liked having chrY counts available for double checking the gender guesses that cnvkit provides, which AFAIK are based on chrX depth.

**Comment by kyleabeauchamp** [comment]
Again, it's not hard for me to work around.

**Comment by etal** [comment]
Were you getting usable off-target chrY counts in male samples? In our panel it's pretty noisy and the chrX signal looks much better. I could be persuaded to change the filter back, but the idea is to drop chrM always, and allow labs to ignore chrY if they aren't specifically interested in it, preferably without resorting to a whitelist for human reference genomes.

**Comment by kyleabeauchamp** [comment]
It's seemed usable to me, but I haven't done anything quantitative with it.

**Comment by etal** [comment]
I'll whitelist `"(chr)?[XY]"` since those two chromosome names get special treatment already.
