### ISSUE TITLE
all 20 samples(tumor +normal ) got a chromosome 6 loss ,is it normal?

### ISSUE THREAD

**Issue by wangjianqing** [etal/cnvkit#392]
I used cnvkit to call cn in 20 paired samples(tumor +normal),and there is strange result ,all samples had a chromosome 6 loss ( chr6:28876582-30916834),and performed GO analysis that most gene focus on the antigen process and interferon-gamma singnal . is it normal?

**Comment by etal** [comment]
That's the HLA region. It's unlikely that this region is really deleted in all of your samples, but there are some potentially read-mapping issues that could give that illusion. When running e.g. BWA-MEM, it's best to remove the alternative contigs from your reference genome so that the read depths on fully assembled chromosomes is more realistic.

Did you run CNVkit separately with each tumor-normal pair? If so, you would probably see better results if you instead pool together all of your normal samples to create a single reference profile (assuming they're all sequenced with the same capture kit), then call CNVs in each tumor sample against that reference. Also consider using the `--drop-low-coverage` option.
