### ISSUE TITLE
How to make segmentation more sensitive and not shifted

### ISSUE THREAD

**Issue by weishwu** [etal/cnvkit#398]
I've used cnvkit to analyze mouse tumor WGS. There is no control sample so I downloaded mouse C57BL/6NJ BAM (which is the same strain as used in the experiment) and used that as the normal control. The total alignment count is about 2 times higher in the control than my samples. I'm concerned that this depth difference can lead to difficulty in deciding cluster centers by cnvkit.

The first plot attached in the end shows the log2 ratio across chromosome 9 for all my 10 samples. The black dots are the log2R at each bin, and the lines are the segments. The color of the segment is green if copy number is estimated to be 2 by cnvkit, and is red if it's a number different from 2. The second plot shows the log2 ratio across chromosome 2 with the same settings. Specifically I have two questions:

1. In samples 6610, 6624 and 6665 (rows 6-8), it's deletion across the entire chromosome. But I'm afraid it's just because the entire cloud of dots somehow got shifted from the line at 0. In sample 6610 (row 6) it shifts upwards, while downwards in 6624 and 6665 (rows 7-8). Does this look like something that is typically caused by the different depth between the control and the tumor samples? Should I manually shift them back by setting a center value for cnvkit? And what makes it more complicated is that different chromosomes behave differently by comparing the two plots. The samples that got shifted in plot 1 appear normal in plot 2, whereas sample 5410 (row 3) seems to be shifted on chromosome 2 (plot 2) but not on chromosome 9 (plot 1). Do I have to shift the centers for each chromosome individually? Is there any systematic way to make cnvkit do this re-centering automatically genome-wide?

2. In sample 5789 (row 5), right after position 4e+07 from x-axis, there are 4 blocks that appear to be CNV (deletion, duplication, deletion and then duplication). But it's a green line across them meaning cnvkit calls all of them as neutral during segmentation. How can I make segmentation more sensitive to capture these blocks correctly?

Thanks.

![chr9_cnvkit](https://user-images.githubusercontent.com/13355007/48870228-f926e100-edad-11e8-9574-54339b351d88.png)

![chr2_cnvkit](https://user-images.githubusercontent.com/13355007/48870546-4e172700-edaf-11e8-9f67-946e55c0ed73.png)

**Comment by etal** [comment]
I agree the problem is in centering these samples. For your second question, sample 5789, I'd manually re-center so that the region from 6e7 onward has a log2 value of zero, i.e. `call --center-at` that segment/region's log2 value.

The default thresholds in `call` for flagging non-neutral regions are chosen to be reasonably sensitive on solid tumor samples. If these samples are mouse cell lines or very pure tumor samples, you can be a bit more stringent in choosing thresholds in `call`. In particular, if you have a decent estimate of tumor cell purity in each sample then you can use `call -m clonal --purity __` (filling in the blank with your purity estimate).

Typically you shouldn't have to re-center each chromosome separately unless something is very wrong/mismatched in your tumor or normal samples. If you have reason to believe the individual chromosomes were subjected to different chemistry or processing, you could manually split the .cns files by chromosome and repeat `call --center` on each of them. But then you'd miss whole-chromosome alterations.

**Comment by weishwu** [comment]
One more question, about the entire-chromosomal CNV, how can I know whether it is true or a centering issue?

**Comment by etal** [comment]
Yes, that would probably lead to some artifacts if the tumor and normal samples went through different lab and sequencing processes. You can use the `call --center` command to fix problems with centering at the end of the analysis, if you need to. Otherwise I suggest looking for better-matched control samples, or repeating the analysis without a control sample for comparison -- the CNV calls that are found by both methods are probably more reliable.
