### ISSUE TITLE
return axis from do_scatter()?

### ISSUE THREAD

**Issue by jeremy9959** [etal/cnvkit#403]
The do_scatter() function should return the matplotlib axis it builds,  like the do_heatmap() function does,  so that the caller can further decorate the graph.

**Comment by etal** [comment]
I agree, thanks for letting me know about this inconsistency.

**Comment by jeremy9959** [comment]
I'd be happy to take a crack at this and put up a pull request.

**Comment by etal** [comment]
Sure, a PR would be awesome. Thanks!

**Comment by jeremy9959** [comment]
Looking at your code, do_scatter sometimes creates a figure with two axes (including cnv and snv info) and sometimes just returns the cnv info -- depends on how it's called.

Might be more natural in this case to return a figure or a tuple of axes, but then it's different from do_heatmap.

Any thoughts on how you'd like this?

**Comment by etal** [comment]
I'm not quite sure whether returning the Figure object or a tuple of Axis objects is more appropriate and user-friendly. I suppose Figure is designed as a container for one or more Axis objects, so that's a slight push toward returning the Figure. The other priority is to keep the code clean, so if you have the Figure readily available, it makes sense to return that.

**Comment by jeremy9959** [comment]
In the end up I put up a PR that returns a figure.  You can retrieve the axes from that.  See what you think.

**Comment by etal** [comment]
Since your PR #408 was merged, this will be in the next release. Thanks!
