### ISSUE TITLE
AssertionError line 309

### ISSUE THREAD

**Issue by trodriguez2011** [etal/cnvkit#406]
I tried cnvkit copy number variation on the latest docker version with and without correlations flag on multiple samples. I'm not sure what's going wrong with this fairly straightforward task. Any help would be greatly appreciated. 

cnvkit.py import-rna cnvbox/cnvbox/46T_S26_l004_L109.rsem.genes.results --gene-resource cnvbox/cnvdata/ensembl-gene-info.hg38.tsv --output output-summary.tsv --output-dir cnvbox/cnvbox/

Traceback (most recent call last):
  File "/usr/local/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/commands.py", line 1461, in _cmd_import_rna
    args.normal, args.do_gc, args.do_txlen, args.max_log2)
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/import_rna.py", line 39, in do_import_rna
    gene_info, sample_counts, tx_lengths, normal_ids)
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/rna.py", line 273, in align_gene_info_to_samples
    normal_ids)
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/rna.py", line 309, in normalize_read_depths
    assert samp

**Comment by etal** [comment]
Thanks for letting me konw. Is there anything unususual about this dataset? It looks like you're processing just one sample, is that true? If so, then this procedure might not work due to its attempts to normalize the input sample(s) as a cohort.

**Comment by trodriguez2011** [comment]
Thank you for your response. I tried again with two samples (normal and tumor) and got the same result:
cnvkit.py import-rna cnvbox/46N_S25_l004_L98.rsem.genes.results cnvbox/46T_S26_l004_L109.rsem.genes.results --gene-resource cnvdata/ensembl-gene-info.hg38.tsv --correlations cnvdata/tcga-skcm.cnv-expr-corr.tsv --output out.tsv --output-dir cnvbox/

Another error I've noticed is " RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import internals as libinternals"

**Comment by etal** [comment]
OK, I think using 1 each of tumor and normal is probably hitting the same edge case in the code. The method is designed to be used with a pool of samples, e.g. >=5 or 10, so that the averages within each sample and each gene can be considered a baseline and rare CNAs will deviate significantly from that baseline. I'll see about handling the T/N case more smoothly, or at least improving the error message.

The RuntimeWarning is safe to ignore. It's due to a sort of harmless disagreement between pandas and numpy that generally does not affect end users, and might go away if both packages are updated to the latest versions. (Or maybe in future releases.)

**Comment by trodriguez2011** [comment]
Fortunately, I discovered that my ensembl IDs were not recognized as they contained a version number. For reasons still unknown, (i) using >3 samples and (ii) separating tumor and normal datasets avoided subsequent errors. 

Thanks for your time!
