### ISSUE TITLE
VCF export and genotype call of deletions

### ISSUE THREAD

**Issue by schelhorn** [etal/cnvkit#41]
In the new VCF export code, you [were writing](https://github.com/etal/cnvkit/blob/3b431edf0ce1d9047a878d5ec768176d21ee0dd1/cnvlib/export.py#L340):

```python
 elif ncopies < ploidy:
            svtype = "DEL"
            svlen *= -1
            formats = "GT:GQ"
            genotype = "0/1:%d" % row["probes"]
```

Does that imply that deletions reported by `cnvkit` will always be called as heterozygous, i.e. no homozygous-alt deletions (`1/1`) can be identified and/or reported?

**Comment by etal** [comment]
I'm aware of two issues here:

1. The new VCF export code doesn't handle haploid chromosomes in otherwise diploid genomes properly. I'll need to refactor the function `call.absolute_pure` and others so that segments with truly neutral copy number can be skipped when iterating through them. This bug applies to BED export, too.

2. Since CNVkit's calls are based on read depth alone (currently), it won't detect copy-number-neutral loss of one allele if it's accompanied by a gain of the other allele, and it won't assign a copy number state to each allele. Is this related to what you were asking? What specific behavior would you like to see?

**Comment by chapmanb** [comment]
Eric and Sven-Eric;
Thanks for all the work on VCF export. I was looking at this in more depth and wanted to follow up on this. Your comments on the haploid/diploid fixes make sense, but for the diploid human-like 2 chromosome case the calls should look like:

- Single copy deletion -- DEL with genotype of 0/1 (as you have right now)
- Deletion with 0 copies -- DEL with genotype of 1/1
- Duplication -- currently this gets assigned a not called genotype (`./.`) which might lead some downstream tools to skip it. Other callers like DELLY provide no calls like this when it finds some evidence of an event but not enough to call it. I don't know if there is a consensus best way to do this since you're not able to assign allele specific mechanisms to alleles but consistently assigning 0/1 or 1/1 in addition to the copy number information you already provide would be an improvement and ensure tools that look at genotypes know CNVkit predicts an event here.

**Comment by etal** [comment]
This works correctly now, right? I'll close this ticket then.
