### ISSUE TITLE
Some questions about cnvkit normal pool from cnvkit examples 

### ISSUE THREAD

**Issue by elizabeth2019** [etal/cnvkit#428]
@etal 

Hi Eric Talevich,

I am trying to build reference using these 10 normal samples(Agilent V4+UTR) :
https://github.com/etal/cnvkit-examples/tree/master/exome

But when I use this reference for my data. I met some problem:
ValueError: Reference is missing *（e.g.10000） bins found in our data. 

Could you please help me to solve this problem? Is it bin size problem?  How should I set the bin size for my data? I used https://github.com/etal/cnvkit-examples/blob/master/intervals/exome-baits.interval_list as target file for my data.

I am also wondering the bin size you used to generate *cnn for these normal samples?

Thanks！

**Comment by etal** [comment]
If you used the same exome target intervals for your own samples, then the off-target bins and subdivided larger on-target bins are probably the issue. The default behaviors have changed since the original reference profile was created, so new bins won't necessarily match the old bins. Instead, to reuse the existing reference.cnn file, you can use the script reference2targets.py to extract the original bin coordinates and use those coordinates to process your own samples, instead of using exome-baits.interval_list.
