### ISSUE TITLE
Filtering Structural variants from CNVkit

### ISSUE THREAD

**Issue by audyavar** [etal/cnvkit#451]
Hello - 

I am using CNVkit to detect structural variants and copy number changes in whole exomeseq data with paired tumor-normal samples. What are the best practices to filter structural variants from exomeseq data? Why are most the variants CNVkit identifies are IMPRECISE variants?

**Comment by etal** [comment]
They're imprecise because CNVkit calls variants only to the nearest bin boundary, which is not necessarily the same (i.e. is probably not the same) as the SV breakpoint. In other words, genomic region binning for the sake of read count calculations is done without knowledge of the likely breakpoints; the bin boundaries are just regular intervals across genome.

You can exclude known problematic regions with the `-x`/`--exclude` option in the `batch` and `antitarget` commands.
