### ISSUE TITLE
scatter finds zero probes when using regions

### ISSUE THREAD

**Issue by ViktorHy** [etal/cnvkit#457]
I have a problem with version 0.9.6. I can plot single chromosomes using the following command:

`cnvkit.py scatter -s Sample.cn{s,r} -c 17 -o 17.png` <- this works

But if I want to plot I defined area say

`cnvkit.py scatter -s Sample.cn{s,r} -c 17:37000000-38000000 -o 17.png` <- this doesn't

Showing 0 probes and 1 selected genes in region 17:35999999-39000000

Similarily if I try to plot only a selected gene.

`cnvkit.py scatter -s Sample.cn{s,r} -g ERBB2`

Showing 0 probes and 1 selected genes....

I tried with an older installation, version 0.9.1 and all the above commands works just fine

**Comment by tetedange13** [comment]
Hi, 
<br>
Had the same bug and it seemed to come from a problem in `_irange_simple()` at this line:
https://github.com/etal/cnvkit/blob/f4ccc908bb3fb07ee701ace63f1f3702ef109f2d/skgenome/intersect.py#L165
*Possible fix:*
`yield (slice(table.index[start_idx], table.index[end_idx]), start_val, end_val)`

*Explanation (guessed):*
The `start_idx and` and `end_idx` in the slice yielded are actually **indexes relative to a subset of "table"**, created within `idx_ranges()`: https://github.com/etal/cnvkit/blob/f4ccc908bb3fb07ee701ace63f1f3702ef109f2d/skgenome/intersect.py#L121
The problem is that coming back to `iter_ranges()`, this slice is **applied to the whole "table"** (full size not subset), to yield a "subtable" object. The indexes being still relative, we catch a **wrong region (often in chrom 1)**. 
<br>
Hope it helps.
Best regards.
Felix.
