### ISSUE TITLE
some questions about bins size

### ISSUE THREAD

**Issue by milkcookie** [etal/cnvkit#467]
Dear all:
when I use cnvkit segment, the result cns file, flow:
![image](https://user-images.githubusercontent.com/20792140/62989023-096d7780-be79-11e9-8b50-554361ae9c25.png)

why the size of bins is so big? I just want to get the exon level CNAs.
best wishes
Hansong

**Comment by etal** [comment]
That's the expected behavior of segmentation -- it groups bins by similar log2 ratio. If you're looking for single-bin testing in order to get exon-level values, you can use the `bintest` command (formerly the separate script `cnv_ztest.py`), or look at the .cnr file directly, possibly with some post-processing or filtering with the `segmetrics` and `call` commands.
