### ISSUE TITLE
Understanding the call --filter option

### ISSUE THREAD

**Issue by sagarutturkar** [etal/cnvkit#469]
Can you please help to understand how the `call --filter` option works. I have an example below for a tumor sample:

### Call without filtering 
`cnvkit.py call --drop-low-coverage T1_tumor.cns -o T1_tumor.call.cns`

![image](https://user-images.githubusercontent.com/7976228/63704941-22bbdf80-c7fa-11e9-85f9-2b68e5a123a5.png)

### Call with filtering
```
cnvkit.py segmetrics T1_tumor.cnr -s T1_tumor.cns  --drop-low-coverage --ci --sem -o T1_tumor.segmetrics.cns
```
![image](https://user-images.githubusercontent.com/7976228/63705749-d376ae80-c7fb-11e9-9997-2962296a6096.png)

```
cnvkit.py call --drop-low-coverage --filter ci T1_tumor.segmetrics.cns -o T1_tumor.call.filtered.cns

```
![image](https://user-images.githubusercontent.com/7976228/63705853-0751d400-c7fc-11e9-9eea-1ed545b3b6b0.png)

### Questions:

1. The actual output from filter has less rows but in most cases, the green highlighted segments are combined together as a single segment. Is this as expected?

2. Also, I see all the `log2` values are within the limits of `ci_lo` and `ci_hi`. I suppose if the value is beyond the limit then segment is excluded? Currently, I don't find such cases in my sample.

3. In `segmetrics` I suppose the `ci_lo` and `ci_hi` are calculated based on the metrics `(--std, --mad, --iqr, --bivar)`, is this correct? What is the default used?

4. The use of `--filter` option is explained under **Germline analysis** section. But it should be equally applicable for the tumor analysis, correct?

**Comment by etal** [comment]
Some details here: https://cnvkit.readthedocs.io/en/stable/pipeline.html#filtering-segments

1 and 2: In general, segments are each evaluated according to some criterion, and then those adjacent segments that are "the same" according to that criterion are merged together, i.e. the breakpoint between them is erased and the resulting segment covers the same bins as the two (or more) original bins.

- For confidence interval filtering (`--ci`), the criterion is whether each segment's confidence interval includes the log2 value 0.0. Those adjacent segments whose CI includes 0.0 are merged together; the remaining segments are left alone.
- For integer copy number merging (`--cn`), the criterion is the `cn` column value. Adjacent segments with the same integer copy number are merged together.

3. The confidence interval is calculated by bootstrapping (`--ci`), not by the summary statistics (other options). The parameter is `--alpha`, default 0.05 in `segmetrics` and 0.5 in `batch`.

4. You can use `--filter` in tumor analysis, too. It's mentioned in the germline tips page because it's common in germline analysis for the number of false positives to be problematic enough to require more automated filtering.

**Comment by kysbbubbu** [comment]
Hello, I have question related to this issue (call --filter ci)
In sagarutturkar's post, can I ask you why segments colored in green merged into the single segment after below command?

cnvkit.py call --drop-low-coverage --filter ci T1_tumor.segmetrics.cns -o T1_tumor.call.filtered.cns

Because all of the ranges of CIs colored in the green did not involve zero value, I anticipated that none of segments would not be filtered. 

Thank you
