### ISSUE TITLE
Heatmap matrix for cnr

### ISSUE THREAD

**Issue by hiroyukikato911** [etal/cnvkit#473]
Hi, 

Thanks for wonderful tool!

Similar to #357 and#365, is there any way to extract multiple cns file matrix for Heatmap using R?

I tried 
cnvkit.py export jtv *.cnr -o Samples-JTV.txt
and it did work, but I want the bins with cns size.

Since cns files consist of different bins, it seems same command didn't work on cns files.

Thank you so much in advance!

**Comment by etal** [comment]
It would require some additional work because the .cns bins don't have the same boundaries across files. With some programming or careful use of `skgenome` you could gather a union set of .cns breakpoints, then subdivide each sample's segments at those breakpoints. The result would be a lot of adjacent segments with identical log2 ratio values, but it should plot fine.

Alternatively, you could iterate over the .cnr files by gene and take the gene-wide average log2 in each. Since you're exporting to R in any case, you could just take the output table from the `genemetrics` command.
