### ISSUE TITLE
With all chromosomes as the abscissa, multiple genes were coded with multiple colors

### ISSUE THREAD

**Issue by axiba053** [etal/cnvkit#474]
![cnv](https://user-images.githubusercontent.com/39181057/66804261-948bec00-ef54-11e9-9a28-709d424dfb0e.png)

I want to encode multiple genes in multiple colors with all the chromosomes as the x-coordinate. Can it be done?How? Just like the picture.
Many thanks!

**Comment by etal** [comment]
This looks like a small target panel where you know the list of genes of interest up front. I think you could manage it with matplotlib by iterating over the .cnr bins by gene, and where the bins are annotated with a gene of interest, plot those points with a color chosen from a color wheel/palette rather than the default gray.

You can see the code in `cnvlib/plots.py` and `cnvlib/scatter.py` for inspiration. I'm not sure exactly which  code will be reusable for this purpose, but `plots.py` will at least give you the genome layout as the basis for your plot.
