### ISSUE TITLE
Questions about log2 threshold of integer copy number

### ISSUE THREAD

**Issue by lrd9** [etal/cnvkit#504]
Hello Eric,
I applied CNVkit to some WES data of cancer samples and found great consistence of CNVkit CNV breakpoint with some splicing abnormalities observed in RNA-seq data. So I want to understand more about the underlying mechanisms of CNVkit. Here I have some questions:

In the cnvkit documents at https://cnvkit.readthedocs.io/en/stable/index.html, the introduciton of `call` function gave several examples:

> cnvkit.py call Sample.cns -o Sample.call.cns

> cnvkit.py call Sample.cns -y -m threshold -t=-1.1,-0.4,0.3,0.7 -o Sample.call.cns

> cnvkit.py call Sample.cns -y -m clonal --purity 0.65 -o Sample.call.cns

> cnvkit.py call Sample.cns -y -v Sample.vcf -m clonal --purity 0.7 -o Sample.call.cns

My questions are:
(1) What will be the threshold of integer copy number when no `-m` parameter was provided (like the first example command line)? Is it still -1.1, -0.4, 0.3, 0.7 ?
(2) If ` -m clonal` and `--purity` are supplied, how would be the threshold be calculated and then used in call function? Is it  ` log2( (1 - purity) + purity * (0:6 + .5) / ploidy )` ?
Thanks in advance!

**Comment by etal** [comment]
Great to hear, and sorry for the delayed response. Your questions:

1. Without specifying `-m`, the default behavior is `-m threshold`. The default thresholds are `-t=-1.1,-0.4,0.3,0.7`, which are reasonable cutoffs for good-quality tumor samples (such as those would work with exome sequencing), and if you want to use those default cutoffs then you don't need to specify them explicitly. The first two example command lines have the same behavior.

2. Yes, the calculation for purity vs. log2 thresholds is the formula saw in the [call command docs](https://cnvkit.readthedocs.io/en/stable/pipeline.html#calling-methods): `log2( (1 - purity) + purity * (0:6 + .5) / ploidy )` (in R), where `0:6` are the absolute integer copy numbers of interest.

**Comment by 2236529177** [comment]
![image](https://user-images.githubusercontent.com/25199946/88457731-4d576200-cebb-11ea-86d9-03188723a378.png)
so with seven values , how you define the following things, a little surprised

    Allowing for random noise of +/- 0.1, the cutoffs are::

        DEL(0)  <  -1.1
        LOSS(1) <  -0.25
        GAIN(3) >=  +0.2
        AMP(4)  >=  +0.7

**Comment by etal** [comment]
The thresholds suggested for tumor analysis are based on some other practical considerations for high-sensitivity diagnostics since the sample purity and tumor clonality presumably aren't known.
- In older literature using SNP arrays for tumor analysis, a cutoff of +/- 0.2 is sometimes used to detect CNAs regardless of sample purity or tumor clonality. For losses, -.2 is a bit too permissive so I stretched it to -.25, catching single-copy losses in tumor clonality as low as 30%, a QC threshold used by some labs.
- DEL and AMP calls are more cautious. If sample purity is close to 100%, then log2 values of -1.0 and +.6 are actually `LOSS(1)` and `GAIN(3)`, respectively. Therefore, log2 values more extreme than those must be more than single-copy losses or gains. I added padding of .1 to account for some stochastic noise and set the limits at -1.1 and +.7 to declare DEL and AMP alterations.

In cases where you do know the sample purity, or at least have a decent estimate of it, it's better to use that value and apply the formula to assign copy number more rigorously.
