### ISSUE TITLE
Query about handling of unmapped MAPQ 0 reads by CNVKIT

### ISSUE THREAD

**Issue by pwanj** [etal/cnvkit#575]
Hello,

I have a BAM file which has unmapped reads of RNAME "*", 0 length and MAPQ 0 . just curious, will cnvkit automatically ignore these? or would you recommend to filter it out before running cnvkit.py script? 

Example 
A@@@@:134:H@@@@@X:1:2114:23583:20823	77	*	0	0	*	*	0	0	*	*	PG:Z:MarkDuplicates	RG:Z:1	AS:i:0	XS:i:0

Any help is much appreciated. Thanks!

Pankhuri

**Comment by tskir** [comment]
Hi @pwanj,

You can see the function which does the read filtering [here](https://github.com/etal/cnvkit/blob/bb519a45eaa79fb7b0c904d83bdb2c1b85607c1f/cnvlib/coverage.py#L128). The reads which are completely unmapped (RNAME "*") will be ignored by the pipeline, so you don't need to do anything special about them.

MAPQ is a different story, because [the default threshold is 0](https://github.com/etal/cnvkit/blob/bb519a45eaa79fb7b0c904d83bdb2c1b85607c1f/cnvlib/commands.py#L486). So if the read _is_ mapped somewhere, then by default it will be counted even if MAPQ is 0. You may raise this threshold by passing a command line argument if you'd like to. **However,** it's been reported that raising this threshold at all (even to as low as 1) can make the results of the pipeline significantly worse. See here for more details: https://github.com/etal/cnvkit/issues/71#issuecomment-170093733

**Comment by tskir** [comment]
Hi @pwanj, just wanted to check if you have any further questions about this, and if not, could you close this issue please? If otherwise, I'll be happy to help.

**Comment by pwanj** [comment]
Thanks so much. Its really helpful.
