### ISSUE TITLE
cnvkit export vcf does not work when nbins is used instead of probes in cns header

### ISSUE THREAD

**Issue by eriktoo** [etal/cnvkit#585]
cnvkit version: 0.9.8

In my pipeline, after generating .cnr files (diploid X) they are processed by genemetrics without segments, then segmetrics (with --gender female to avoid shifting X log2s) to get statistics, and finally with call. Exporting the final call .cns to bed format works fine, but when exporting to vcf the files contain only the header and no cnvs. When running a pipeline that does normal segmentation instead of genemetrics export to vcf works. The only difference in the header is that the genemetrics case has a column 'n_bins' and the regular segmentation a column 'probes'.

The responsible line in export.py is 266, which does not check for the presence of n_bins or probes and assumes the latter:

`    out_dframe = segments.data.reindex(columns=["chromosome", "end", "log2", "probes"])`

A quick fix is to run the files with n_bins through sed to convert to probes:

`sed s/n_bins/probes/ $file`

**Comment by tskir** [comment]
We might need to wait for @etal's opinion here, but I don't think the `export` command was intended to support this case. One of the fields in the output VCF is:

```
##INFO=<ID=PROBES,Number=1,Type=Integer,Description="Number of probes in CNV">
```

Since the CNS from genemetrics does not have the `probes` column, and because the number of probes is _not_ generally the same as the number of bins (as each bin can contain more than one probe), there just isn't enough information to generate the output VCF.

**Comment by tskir** [comment]
On the other hand, what we could do is just retain the `probes` column in the genemetrics output. I don't see why not, since this can be a useful metric.

**Comment by tskir** [comment]
No, wait, I'm wrong. CNN/CNR already contain bins, not the original probes. So the `probes` in regular CNS and `n_bins` in genemetrics CNS are exactly the same thing, just differently named. I suppose this can be fixed to make things consistent & allow calling from the genemetrics CNS as well.

**Comment by etal** [comment]
It did not occur to me to try running the `genemetrics` output table through `export vcf`, and I'm impressed you got this far.

I agree with @tskir 's solution to just change the header of the genemetrics output table to use `probes` instead of `n_bins`. (I wrote the genemetrics code long after the segmentation code, and I like the semantics of "n_bins" better than "probes", but it would be too disruptive to change the .cnr and .cns headers now.)
