### ISSUE TITLE
Modify width/height for output figure generated from scatter command

### ISSUE THREAD

**Issue by asaki1986** [etal/cnvkit#600]
Hi,

As cnvkit provide a great convenience to analyze the CNV status of the sample.
One can generate a CNV call plot from the cns and cnr data.

I am wondering if I can give a option to set the width/height/resolution of the output png figure, for either whole genome or selected region/chr?

Thanks,
Junfeng

**Comment by tskir** [comment]
Hi @asaki1986,

Unfortunately, at this point you cannot adjust any export parameters for PNG files generated by CNVkit.

To achieve higher resolution, you could export the plots in either SVG or PDF (this is done by simply running the `cnvkit.py scatter` command with `-o plot_name.svg` or `-o plot_name.pdf` flags, respectively). This allows you to get publication quality vector graphs and then export them into PNG using any resolution settings. Again, unfortunately, the height and width of this output graph still cannot be adjusted.

The plotting system in CNVkit would definitely benefit from a refactor, so I'm going to leave this ticket up as a feature request; but I'm afraid it is unlikely to be done in any sort of a foreseeable future, because I am only able to dedicate a few hours a week to this project.

**Comment by stacyhung** [comment]
You can change the y-axis limits with `--y-min` and `--y-max` (using a range of [-4, 4] works well for most samples).  This might help increase the resolution since there are often a small number of outliers that causes the height of the plot to be much larger than necessary.
