### ISSUE TITLE
CN from log2 is inaccurate at times

### ISSUE THREAD

**Issue by ashbig** [etal/cnvkit#626]
In brief, there seems to be issues calling copy number from log2. This is from a no template control run in our lab. The depths and log2 are both accurate, but the CN call shows a gain of 8. I've also observed CN being off by a few copies than what is expected from the log2 and I can dig up more examples if helpful. 

# code for 0.9.6
cnvkit.py call ${cns} -o ${segs}
cnvkit.py genemetrics ${segs} --stdev --ci -o ${s_gainloss}

gene    chromosome      start   end     log2    cn      depth   weight  n_bins
DDR2    chr1    162688843       162750046       -4.06365        8       1.49628 10.3477 16

**Comment by tetedange13** [comment]
Hi @ashbig ,

Not an author of CNVkit, but would it be possible for you to **upgrade to latest release of CNVkit**?
=> A lot of things were fixed/improved since CNVkit v0.9.6
=> So if you can, tell us if you still got same inconsistant CN values with CNVkit v0.9.9

Have nice day.
Kind regards.
Felix.

**Comment by tskir** [comment]
Hi @ashbig, I was wondering if you had the chance to try this with CNVkit v0.9.9?

**Comment by ashbig** [comment]
@tskir @tetedange13 

I did upgrade and test in CNVkit v0.9.9 and I no longer see the inconsistency. However in upgrading I re-read the documentation and observed that my call command was executed incorrectly.  The gene-metrics command also requires the .cnr file which I was failing to provide.
