### ISSUE TITLE
Script for cn_ztest.py not available. Posted on Biostars

### ISSUE THREAD

**Issue by skose82** [etal/cnvkit#649]

**Comment by SKose9** [comment]
Posted by Eric T. However, link is no longer working. Is there another way to plot log2 scores? https://www.biostars.org/p/272590/

**Comment by tetedange13** [comment]
Hi @SKose9 ,

Not an author of CNVkit, but since latest version, `cnv_ztest.py` script were replaced by a dedicated subcommand `cnvkit.py bintest` (see [this release note](https://github.com/etal/cnvkit/releases/tag/v0.9.7.b1))
=> Some bugs were fixed too, so please update to latest version
=> We are working to add this to CNVkit documentation soon

Hope this helps.
Have a nice day.
Felix.

**Comment by SKose9** [comment]
Thank you for your response. It was most helpful. In addition, Is there a way to see the bintest result in a plot of some sort? I'm trying to detect exon deletions in particular. I would like to zoom in on a chromosome to visually see if, say, an exon has been deleted in a particular region/gene, currently I can produce a scatter plot that displays everything (chr1-chrM). I can't quite see where to do this in the manual/docs. 
![sample1_scatter](https://user-images.githubusercontent.com/32903403/127476227-c519a2f1-5e2c-4fd8-b915-382613b742fd.jpg)
