### ISSUE TITLE
CNVkit batch command cannot recognise bed file format

### ISSUE THREAD

**Issue by HasibAhmed1996** [etal/cnvkit#696]
I'm currently doing my master's thesis on WES analysis and I need help regarding CNVkit. I've followed the documentation of CNVkit website and have also downloaded BED files from Agilent sureselect website. For some reason, cnvkit.py batch ....... always returns with "BED file in incorrect format" when it literally is a .bed file. I don't know how to get around this problem. Please help.
I am attaching photos of the command I wrote, the error message and also first few lines of my bed file.
![IMG_20220222_183721__01](https://user-images.githubusercontent.com/72304117/155134685-0dc5bad2-3a81-4d32-b4b9-9e08246980f3.jpg)
![IMG_20220222_183802__01](https://user-images.githubusercontent.com/72304117/155134704-95bdef9f-b2b4-455e-95b5-a2f77a06acba.jpg)
![IMG_20220222_183904__01__01](https://user-images.githubusercontent.com/72304117/155134737-db952703-e69a-44a3-b69d-bc22c36568cb.jpg)

**Comment by tetedange13** [comment]
Hi @HasibAhmed1996,
<br>

Try to create a 2nd BED file without any header (first 2 lines starting by "browser" and "track")
=> Something like that: `awk 'NR>2' S31285117_Regions.bed > S31285117_Regions-NOhead.bed` 
=> Then re-run your `batch` command with this BED instead and tell us 

Also for your future issues, please avoid reporting your outputs and command-lines as pictures (as they are way heavier)
=> Better use simple text with with dedicated Markdown syntax! See: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting
=> Anyway, thanks for providing details !
<br>

Hope this helps.
Have a nice day.
Felix.

**Comment by tetedange13** [comment]
Notes for possible enhancement:

* IMHO above issue occured because following line if not covering this specific case with 2 header lines:
https://github.com/etal/cnvkit/blob/75274557b7c5770132f9bfc8b18ca9844e91ba96/skgenome/tabio/__init__.py#L229-L232
* Most Agilent BED files look like that (1st line = "browser position ..." ; 2nd = "track ...")
* A fix could be: `if line.startswith('track') or line.startswith('browser'):`

Instead of trying to cover every case, maybe simply specify somewhere in CNVkit documentation that BED files *should not* have a header ?
=> Actually this is mostly true for all files given as input to CNVkit (thinking at #618 )
<br>

Felix.

**Comment by etal** [comment]
Thanks, Felix. Since most Agilent BED files include both these header lines and I think they are valid UCSC BED features, I'm inclined to check for both possibilities in the same `if` statement as you suggested.

**Comment by HasibAhmed1996** [comment]
Thank you so much, Felix. Removing the first 2 lines from the bed file worked perfectly!
