### ISSUE TITLE
Pooled reference

### ISSUE THREAD

**Issue by YingYa** [etal/cnvkit#85]
I have 5 normal sample, 3 of them are male, and others are female.
Should I combine all normal samples into a pooled reference or I need to combine males and females into different pooled reference?

**Comment by etal** [comment]
You can use them all in the same pooled reference -- CNVkit should detect the gender of each normal sample and adjust the X-chromosome values accordingly. The detected genders will be logged so you can verify it was done correctly.

**Comment by jsmedmar** [comment]
@etal, thanks again for your contributions to this great tool. I do have a question about this issue, the docs state: 

```
The expected and observed ploidy of the sex chromosomes (X and Y) is different, so it’s 
important to specify -y/--male-reference if a male reference was used; the sample sex can be 
specified if known, otherwise it will be guessed from the average log2 ratio of chromosome X.
```

If one has pooled normal of mixed gender, then it's not necessary to pass the `--male-reference` flag, correct?

**Comment by etal** [comment]
It's technically not necessary either way:
http://cnvkit.readthedocs.io/en/stable/sex.html

In `reference`, the chromosomal sex of the normal samples is automatically inferred on the fly, and X and Y ploidy is adjusted to make the output reference .cnn look like either XY (with `-y`/`--male-reference`) or XX (default, without `-y`/`--male-reference`). If you know you want a reference profile with haploid X (e.g. to resemble aCGH assays), use the `-y` flag in both `reference` and `call`; otherwise, don't.

**Comment by jsmedmar** [comment]
@etal let me present this example. I compute a `reference.cnn` file using a pool of both female and male individuals.

Now, given the case I want to use this pooled `reference.cnn` on a MALE individual, should I pass the `--male-reference` flag? (I assume it will only be used in the `call` step)

Please excuse if I'm just being slow with this.

**Comment by etal** [comment]
Nope, regardless of your samples you can safely ignore the `--male-reference` option. No need to use it.

A pooled reference of male and female samples is fine.
